# Lab 23: Needham-Schroeder Protocol Simulation
import secrets

def simulate_ns():
    print("--- Needham-Schroeder Simulation ---")
    
    # Alice (A), Bob (B), Server (S)
    Na = secrets.token_hex(4) # Nonce A
    print(f"Step 1: A -> S: Request session with B, Nonce={Na}")
    
    Ks = "SECRET_KEY_123" # Session Key generated by Server
    print(f"Step 2: S -> A: Sending Session Key and Ticket for B")
    
    print(f"Step 3: A -> B: Sending Ticket (Contains Ks)")
    
    Nb = secrets.token_hex(4) # Nonce B
    print(f"Step 4: B -> A: Challenge with Nonce={Nb}")
    
    response = hex(int(Nb, 16) - 1)
    print(f"Step 5: A -> B: Correct response {response}. Auth Complete.")

simulate_ns()